/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testmathisi1;

/**
 *
 * @author babis
 */
public class Exam1GUI extends javax.swing.JFrame {
    String ans1;
    String ans2;
    String ans3;
    String ans4;
    String ans5;
    String ans6;
    String ans7;
    String ans8;
    /**
     * Creates new form Exam1GUI
     */
    public Exam1GUI() {
        initComponents();
        ans1="false1,";
        ans2="false2,";
        ans3="false3,";
        ans4="false4,";
        ans5="false5,";
        ans6="false6,";
        ans7="false7,";
        ans8="false8";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        E1buttonGroup1 = new javax.swing.ButtonGroup();
        E1buttonGroup2 = new javax.swing.ButtonGroup();
        E1buttonGroup3 = new javax.swing.ButtonGroup();
        E1buttonGroup4 = new javax.swing.ButtonGroup();
        E1buttonGroup5 = new javax.swing.ButtonGroup();
        E1buttonGroup6 = new javax.swing.ButtonGroup();
        E1buttonGroup7 = new javax.swing.ButtonGroup();
        E1buttonGroup8 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        E1Btn1n1 = new javax.swing.JRadioButton();
        E1Btn1n2 = new javax.swing.JRadioButton();
        E1Btn1n3 = new javax.swing.JRadioButton();
        E1Btn1n4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        E1Btn2n1 = new javax.swing.JRadioButton();
        E1Btn2n2 = new javax.swing.JRadioButton();
        E1Btn2n3 = new javax.swing.JRadioButton();
        E1Btn2n4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        E1Btn3n1 = new javax.swing.JRadioButton();
        E1Btn3n2 = new javax.swing.JRadioButton();
        E1Btn3n3 = new javax.swing.JRadioButton();
        E1Btn3n4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        E1Btn4n1 = new javax.swing.JRadioButton();
        E1Btn4n2 = new javax.swing.JRadioButton();
        E1Btn4n3 = new javax.swing.JRadioButton();
        E1Btn4n4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        E1Btn5n1 = new javax.swing.JRadioButton();
        E1Btn5n2 = new javax.swing.JRadioButton();
        E1Btn5n3 = new javax.swing.JRadioButton();
        E1Btn5n4 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        E1Sosto1 = new javax.swing.JRadioButton();
        E1Lathos1 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        E1Sosto2 = new javax.swing.JRadioButton();
        E1Lathos2 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        Ε1Sosto3 = new javax.swing.JRadioButton();
        Ε1Lathos3 = new javax.swing.JRadioButton();
        Submit1Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("1) Πότε γεννήθηκε η κοινωνιολογία στην Δυτική Ευρώπη;");

        E1buttonGroup1.add(E1Btn1n1);
        E1Btn1n1.setText("1789");
        E1Btn1n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn1n1ActionPerformed(evt);
            }
        });

        E1buttonGroup1.add(E1Btn1n2);
        E1Btn1n2.setText("1689");
        E1Btn1n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn1n2ActionPerformed(evt);
            }
        });

        E1buttonGroup1.add(E1Btn1n3);
        E1Btn1n3.setText("1768");
        E1Btn1n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn1n3ActionPerformed(evt);
            }
        });

        E1buttonGroup1.add(E1Btn1n4);
        E1Btn1n4.setText("1881");
        E1Btn1n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn1n4ActionPerformed(evt);
            }
        });

        jLabel2.setText("2) Πότε έγινε η Γαλλική Επανάσταση;");

        E1buttonGroup2.add(E1Btn2n1);
        E1Btn2n1.setText("1679");
        E1Btn2n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn2n1ActionPerformed(evt);
            }
        });

        E1buttonGroup2.add(E1Btn2n2);
        E1Btn2n2.setText("1789");
        E1Btn2n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn2n2ActionPerformed(evt);
            }
        });

        E1buttonGroup2.add(E1Btn2n3);
        E1Btn2n3.setText("1668");
        E1Btn2n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn2n3ActionPerformed(evt);
            }
        });

        E1buttonGroup2.add(E1Btn2n4);
        E1Btn2n4.setText("1778");
        E1Btn2n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn2n4ActionPerformed(evt);
            }
        });

        jLabel3.setText("3) Ποιές αλλαγές συγκλόνισαν την ευρωπαϊκή κοινωνική πραγματικότητα του 18ου αιώνα;");

        E1buttonGroup3.add(E1Btn3n1);
        E1Btn3n1.setText("Εισαγωγή της μηχανής στην εργασία");
        E1Btn3n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn3n1ActionPerformed(evt);
            }
        });

        E1buttonGroup3.add(E1Btn3n2);
        E1Btn3n2.setText("Ανάπτυξη του σιδηροδρομικού δικτύου");
        E1Btn3n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn3n2ActionPerformed(evt);
            }
        });

        E1buttonGroup3.add(E1Btn3n3);
        E1Btn3n3.setText("Έξοδος των αγροτών από την ύπαιθρο");
        E1Btn3n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn3n3ActionPerformed(evt);
            }
        });

        E1buttonGroup3.add(E1Btn3n4);
        E1Btn3n4.setText("Όλα τα παραπάνω");
        E1Btn3n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn3n4ActionPerformed(evt);
            }
        });

        jLabel4.setText("4) Ποιόν αιώνα ξεκίνησε η βιομηχανική επανάσταση στην Αγγλία; ");

        E1buttonGroup4.add(E1Btn4n1);
        E1Btn4n1.setText("18o");
        E1Btn4n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn4n1ActionPerformed(evt);
            }
        });

        E1buttonGroup4.add(E1Btn4n2);
        E1Btn4n2.setText("16o");
        E1Btn4n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn4n2ActionPerformed(evt);
            }
        });

        E1buttonGroup4.add(E1Btn4n3);
        E1Btn4n3.setText("17o");
        E1Btn4n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn4n3ActionPerformed(evt);
            }
        });

        E1buttonGroup4.add(E1Btn4n4);
        E1Btn4n4.setText("19o");
        E1Btn4n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn4n4ActionPerformed(evt);
            }
        });

        jLabel5.setText("5) Τι προκάλεσαν οι αλλαγές στην ευρωπαϊκή κοινωνική πραγματικότητα του 18ου αιώνα; ");

        E1buttonGroup5.add(E1Btn5n1);
        E1Btn5n1.setText("Ανασφάλεια και ανησυχία");
        E1Btn5n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn5n1ActionPerformed(evt);
            }
        });

        E1buttonGroup5.add(E1Btn5n2);
        E1Btn5n2.setText("Ηρεμία και τάξη ");
        E1Btn5n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn5n2ActionPerformed(evt);
            }
        });

        E1buttonGroup5.add(E1Btn5n3);
        E1Btn5n3.setText("Απαλοιφή κοινωνικών προβλημάτων ");
        E1Btn5n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn5n3ActionPerformed(evt);
            }
        });

        E1buttonGroup5.add(E1Btn5n4);
        E1Btn5n4.setText("Εδραίωση παλαιών κοινωνικών θεσμών");
        E1Btn5n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Btn5n4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Α) Ερωτήσεις πολλαπλής επιλογής:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Β) Ερωτήσεις σωστού-λάθους:");

        jLabel8.setText("1) Η κοινωνιολογία έχει ως αντικείμενο μελέτης τα κοινωνικά φαινόμενα, τη δράση των κοινωνικών ομάδων, τις σχέσεις μεταξύ ατόμου και ομάδων, τις σχέσεις μεταξύ κοινωνικών ομάδων και τις κοινωνικές διαδικασίες. ");

        E1buttonGroup6.add(E1Sosto1);
        E1Sosto1.setText("Σωστό");
        E1Sosto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Sosto1ActionPerformed(evt);
            }
        });

        E1buttonGroup6.add(E1Lathos1);
        E1Lathos1.setText("Λάθος");
        E1Lathos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Lathos1ActionPerformed(evt);
            }
        });

        jLabel9.setText("2) Ιστορικές μελέτες έδειξαν πως στην Ευρώπη του Μεσσαίωνα σχεδόν κανείς δεν παντρευόταν από έρωτα.");

        E1buttonGroup7.add(E1Sosto2);
        E1Sosto2.setText("Σωστό");
        E1Sosto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Sosto2ActionPerformed(evt);
            }
        });

        E1buttonGroup7.add(E1Lathos2);
        E1Lathos2.setText("Λάθος");
        E1Lathos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1Lathos2ActionPerformed(evt);
            }
        });

        jLabel10.setText("3) Κατά τον 18ο αιώνα δημιουργήθηκαν νέοι κοινωνικοί δεσμοί, ήθη και έθιμα λόγω των κοινωνικών αλλαγών της περιόδου εκείνης. ");

        E1buttonGroup8.add(Ε1Sosto3);
        Ε1Sosto3.setText("Σωστό");
        Ε1Sosto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ε1Sosto3ActionPerformed(evt);
            }
        });

        E1buttonGroup8.add(Ε1Lathos3);
        Ε1Lathos3.setText("Λάθος");
        Ε1Lathos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ε1Lathos3ActionPerformed(evt);
            }
        });

        Submit1Btn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Submit1Btn.setText("Submit");
        Submit1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit1BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(E1Sosto1)
                        .addGap(37, 37, 37)
                        .addComponent(E1Lathos1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(E1Sosto2)
                        .addGap(35, 35, 35)
                        .addComponent(E1Lathos2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 662, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(E1Btn5n1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(E1Btn5n2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(E1Btn5n3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(E1Btn5n4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(E1Btn4n1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(E1Btn4n2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(E1Btn4n3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(E1Btn4n4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(E1Btn3n1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(E1Btn3n2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(E1Btn3n3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(E1Btn3n4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(E1Btn2n1)
                                .addGap(18, 18, 18)
                                .addComponent(E1Btn2n2)
                                .addGap(18, 18, 18)
                                .addComponent(E1Btn2n3)
                                .addGap(18, 18, 18)
                                .addComponent(E1Btn2n4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(E1Btn1n1)
                                .addGap(18, 18, 18)
                                .addComponent(E1Btn1n2)
                                .addGap(18, 18, 18)
                                .addComponent(E1Btn1n3)
                                .addGap(18, 18, 18)
                                .addComponent(E1Btn1n4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(Ε1Sosto3)
                .addGap(36, 36, 36)
                .addComponent(Ε1Lathos3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Submit1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E1Btn1n1)
                    .addComponent(E1Btn1n2)
                    .addComponent(E1Btn1n3)
                    .addComponent(E1Btn1n4))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E1Btn2n1)
                    .addComponent(E1Btn2n2)
                    .addComponent(E1Btn2n3)
                    .addComponent(E1Btn2n4))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E1Btn3n1)
                    .addComponent(E1Btn3n2)
                    .addComponent(E1Btn3n3)
                    .addComponent(E1Btn3n4))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E1Btn4n1)
                    .addComponent(E1Btn4n2)
                    .addComponent(E1Btn4n3)
                    .addComponent(E1Btn4n4))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E1Btn5n1)
                    .addComponent(E1Btn5n2)
                    .addComponent(E1Btn5n3)
                    .addComponent(E1Btn5n4))
                .addGap(26, 26, 26)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E1Sosto1)
                    .addComponent(E1Lathos1))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E1Sosto2)
                    .addComponent(E1Lathos2))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ε1Sosto3)
                            .addComponent(Ε1Lathos3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Submit1Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit1BtnActionPerformed
        // TODO add your handling code here:
        ExamGui frameT = new ExamGui();
        frameT.setTitle("Διαγώνισμα");
        frameT.setVisible(true);
        frameT.setResizable(true);
        frameT.setLocationRelativeTo(null);
        super.dispose();
        System.out.print("Exam1GUI: " + ans1 + ans2 + ans3 + ans4 + ans5 + ans6 + ans7 +ans8);
        CreateFile.create();
        WriteToFile.write("Exam1GUI: ");
        WriteToFile.write(ans1 + ans2 + ans3 + ans4 + ans5 + ans6 + ans7 +ans8);
    }//GEN-LAST:event_Submit1BtnActionPerformed

    private void E1Btn1n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn1n1ActionPerformed
        // TODO add your handling code here:
        ans1="true1,";
    }//GEN-LAST:event_E1Btn1n1ActionPerformed

    private void E1Btn1n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn1n2ActionPerformed
        // TODO add your handling code here:
        ans1="false1,";
    }//GEN-LAST:event_E1Btn1n2ActionPerformed

    private void E1Btn1n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn1n3ActionPerformed
        // TODO add your handling code here:
        ans1="false1,";
    }//GEN-LAST:event_E1Btn1n3ActionPerformed

    private void E1Btn1n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn1n4ActionPerformed
        // TODO add your handling code here:
        ans1="false1,";
    }//GEN-LAST:event_E1Btn1n4ActionPerformed

    private void E1Btn2n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn2n1ActionPerformed
        // TODO add your handling code here:
        ans2="false2,";
    }//GEN-LAST:event_E1Btn2n1ActionPerformed

    private void E1Btn2n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn2n2ActionPerformed
        // TODO add your handling code here:
        ans2="true2,";
    }//GEN-LAST:event_E1Btn2n2ActionPerformed

    private void E1Btn2n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn2n3ActionPerformed
        // TODO add your handling code here:
        ans2="false2,";
    }//GEN-LAST:event_E1Btn2n3ActionPerformed

    private void E1Btn2n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn2n4ActionPerformed
        // TODO add your handling code here:
        ans2="false2,";
    }//GEN-LAST:event_E1Btn2n4ActionPerformed

    private void E1Btn3n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn3n1ActionPerformed
        // TODO add your handling code here:
        ans3="false3,";
    }//GEN-LAST:event_E1Btn3n1ActionPerformed

    private void E1Btn3n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn3n2ActionPerformed
        // TODO add your handling code here:
        ans3="false3,";
    }//GEN-LAST:event_E1Btn3n2ActionPerformed

    private void E1Btn3n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn3n3ActionPerformed
        // TODO add your handling code here:
        ans3="false3,";
    }//GEN-LAST:event_E1Btn3n3ActionPerformed

    private void E1Btn3n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn3n4ActionPerformed
        // TODO add your handling code here:
        ans3="true3,";
    }//GEN-LAST:event_E1Btn3n4ActionPerformed

    private void E1Btn4n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn4n1ActionPerformed
        // TODO add your handling code here:
        ans4="true4,";
    }//GEN-LAST:event_E1Btn4n1ActionPerformed

    private void E1Btn4n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn4n2ActionPerformed
        // TODO add your handling code here:
        ans4="false4,";
    }//GEN-LAST:event_E1Btn4n2ActionPerformed

    private void E1Btn4n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn4n3ActionPerformed
        // TODO add your handling code here:
        ans4="false4,";
    }//GEN-LAST:event_E1Btn4n3ActionPerformed

    private void E1Btn4n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn4n4ActionPerformed
        // TODO add your handling code here:
        ans4="false4,";
    }//GEN-LAST:event_E1Btn4n4ActionPerformed

    private void E1Btn5n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn5n1ActionPerformed
        // TODO add your handling code here:
        ans5="true5,";
    }//GEN-LAST:event_E1Btn5n1ActionPerformed

    private void E1Btn5n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn5n2ActionPerformed
        // TODO add your handling code here:
        ans5="false5,";
    }//GEN-LAST:event_E1Btn5n2ActionPerformed

    private void E1Btn5n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn5n3ActionPerformed
        // TODO add your handling code here:
        ans5="false5,";
    }//GEN-LAST:event_E1Btn5n3ActionPerformed

    private void E1Btn5n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Btn5n4ActionPerformed
        // TODO add your handling code here:
        ans5="false5,";
    }//GEN-LAST:event_E1Btn5n4ActionPerformed

    private void E1Sosto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Sosto1ActionPerformed
        // TODO add your handling code here:
        ans6="true6,";
    }//GEN-LAST:event_E1Sosto1ActionPerformed

    private void E1Lathos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Lathos1ActionPerformed
        // TODO add your handling code here:
        ans6="false6,";
    }//GEN-LAST:event_E1Lathos1ActionPerformed

    private void E1Sosto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Sosto2ActionPerformed
        // TODO add your handling code here:
        ans7="true7,";
    }//GEN-LAST:event_E1Sosto2ActionPerformed

    private void E1Lathos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1Lathos2ActionPerformed
        // TODO add your handling code here:
        ans7="false7,";
    }//GEN-LAST:event_E1Lathos2ActionPerformed

    private void Ε1Sosto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ε1Sosto3ActionPerformed
        // TODO add your handling code here:
        ans8="true8";
    }//GEN-LAST:event_Ε1Sosto3ActionPerformed

    private void Ε1Lathos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ε1Lathos3ActionPerformed
        // TODO add your handling code here:
        ans8="false8";
    }//GEN-LAST:event_Ε1Lathos3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exam1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exam1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exam1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exam1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exam1GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton E1Btn1n1;
    private javax.swing.JRadioButton E1Btn1n2;
    private javax.swing.JRadioButton E1Btn1n3;
    private javax.swing.JRadioButton E1Btn1n4;
    private javax.swing.JRadioButton E1Btn2n1;
    private javax.swing.JRadioButton E1Btn2n2;
    private javax.swing.JRadioButton E1Btn2n3;
    private javax.swing.JRadioButton E1Btn2n4;
    private javax.swing.JRadioButton E1Btn3n1;
    private javax.swing.JRadioButton E1Btn3n2;
    private javax.swing.JRadioButton E1Btn3n3;
    private javax.swing.JRadioButton E1Btn3n4;
    private javax.swing.JRadioButton E1Btn4n1;
    private javax.swing.JRadioButton E1Btn4n2;
    private javax.swing.JRadioButton E1Btn4n3;
    private javax.swing.JRadioButton E1Btn4n4;
    private javax.swing.JRadioButton E1Btn5n1;
    private javax.swing.JRadioButton E1Btn5n2;
    private javax.swing.JRadioButton E1Btn5n3;
    private javax.swing.JRadioButton E1Btn5n4;
    private javax.swing.JRadioButton E1Lathos1;
    private javax.swing.JRadioButton E1Lathos2;
    private javax.swing.JRadioButton E1Sosto1;
    private javax.swing.JRadioButton E1Sosto2;
    private javax.swing.ButtonGroup E1buttonGroup1;
    private javax.swing.ButtonGroup E1buttonGroup2;
    private javax.swing.ButtonGroup E1buttonGroup3;
    private javax.swing.ButtonGroup E1buttonGroup4;
    private javax.swing.ButtonGroup E1buttonGroup5;
    private javax.swing.ButtonGroup E1buttonGroup6;
    private javax.swing.ButtonGroup E1buttonGroup7;
    private javax.swing.ButtonGroup E1buttonGroup8;
    private javax.swing.JButton Submit1Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton Ε1Lathos3;
    private javax.swing.JRadioButton Ε1Sosto3;
    // End of variables declaration//GEN-END:variables
}
