/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testmathisi1;

/**
 *
 * @author babis
 */
public class Exam2GUI extends javax.swing.JFrame {
    String ans1;
    String ans2;
    String ans3;
    String ans4;
    String ans5;
    String ans6;
    String ans7;
    /**
     * Creates new form Exam2GUI
     */
    public Exam2GUI() {
        initComponents();
        ans1="false1,";
        ans2="false2,";
        ans3="false3,";
        ans4="false4,";
        ans5="false5,";
        ans6="false6,";
        ans7="false7";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        E2buttonGroup1 = new javax.swing.ButtonGroup();
        E2buttonGroup2 = new javax.swing.ButtonGroup();
        E2buttonGroup3 = new javax.swing.ButtonGroup();
        E2buttonGroup4 = new javax.swing.ButtonGroup();
        E2buttonGroup5 = new javax.swing.ButtonGroup();
        E2buttonGroup6 = new javax.swing.ButtonGroup();
        E2buttonGroup7 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        E2Btn1n1 = new javax.swing.JRadioButton();
        E2Btn1n2 = new javax.swing.JRadioButton();
        E2Btn1n3 = new javax.swing.JRadioButton();
        E2Btn1n4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        E2Btn2n1 = new javax.swing.JRadioButton();
        E2Btn2n2 = new javax.swing.JRadioButton();
        E2Btn2n3 = new javax.swing.JRadioButton();
        E2Btn2n4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        E2Btn3n1 = new javax.swing.JRadioButton();
        E2Btn3n2 = new javax.swing.JRadioButton();
        E2Btn3n3 = new javax.swing.JRadioButton();
        E2Btn3n4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        E2Btn4n1 = new javax.swing.JRadioButton();
        E2Btn4n2 = new javax.swing.JRadioButton();
        E2Btn4n3 = new javax.swing.JRadioButton();
        E2Btn4n4 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        E2Sosto1 = new javax.swing.JRadioButton();
        E2Lathos1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        E2Sosto2 = new javax.swing.JRadioButton();
        E2Lathos2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        E2Sosto3 = new javax.swing.JRadioButton();
        E2Lathos3 = new javax.swing.JRadioButton();
        Submit2Btn = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Α) Ερωτήσεις πολλαπλής επιλογής:");

        jLabel2.setText("1) Σε ποιό στάδιο του ανθρώπινου πνεύματος ο άνθρωπος παρατηρεί τα φαινόμενα και ανακαλύπτει τους  νόμους που τα διέπουν;");

        E2buttonGroup1.add(E2Btn1n1);
        E2Btn1n1.setText("θετικό");
        E2Btn1n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Btn1n1ActionPerformed(evt);
            }
        });

        E2buttonGroup1.add(E2Btn1n2);
        E2Btn1n2.setText("θεολογικό");
        E2Btn1n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Btn1n2ActionPerformed(evt);
            }
        });

        E2buttonGroup1.add(E2Btn1n3);
        E2Btn1n3.setText("μεταφυσικό");
        E2Btn1n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Btn1n3ActionPerformed(evt);
            }
        });

        E2buttonGroup1.add(E2Btn1n4);
        E2Btn1n4.setText("Όλα τα παραπάνω");
        E2Btn1n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Btn1n4ActionPerformed(evt);
            }
        });

        jLabel3.setText("2) Ποιά φάση της εξέλιξης του τρόπου σκέψης του ανθρώπινου πνεύματος πίστευε ο Κοντ πως ήταν η  κορυφαία;");

        E2buttonGroup2.add(E2Btn2n1);
        E2Btn2n1.setText("θετικό");
        E2Btn2n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Btn2n1ActionPerformed(evt);
            }
        });

        E2buttonGroup2.add(E2Btn2n2);
        E2Btn2n2.setText("θεολογικό");
        E2Btn2n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Btn2n2ActionPerformed(evt);
            }
        });

        E2buttonGroup2.add(E2Btn2n3);
        E2Btn2n3.setText("μεταφυσικό");
        E2Btn2n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Btn2n3ActionPerformed(evt);
            }
        });

        E2buttonGroup2.add(E2Btn2n4);
        E2Btn2n4.setText("Όλα τα παραπάνω");
        E2Btn2n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Btn2n4ActionPerformed(evt);
            }
        });

        jLabel4.setText("3) Ποιό σύστημα ανέλυσε Ο Μαρξ ως μέσων παραγωγής, προϊόντων και εμπορευμάτων που παράγονται  με τη μίσθωση εργατών;");

        E2buttonGroup3.add(E2Btn3n1);
        E2Btn3n1.setText("Καπιταλιστικό");
        E2Btn3n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Btn3n1ActionPerformed(evt);
            }
        });

        E2buttonGroup3.add(E2Btn3n2);
        E2Btn3n2.setText("Φεουδαρχικό");
        E2Btn3n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Btn3n2ActionPerformed(evt);
            }
        });

        E2buttonGroup3.add(E2Btn3n3);
        E2Btn3n3.setText("Ολιγαρχικό");
        E2Btn3n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Btn3n3ActionPerformed(evt);
            }
        });

        E2buttonGroup3.add(E2Btn3n4);
        E2Btn3n4.setText("Σοσιαλιστικό");
        E2Btn3n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Btn3n4ActionPerformed(evt);
            }
        });

        jLabel5.setText("4) Σε ποιό στάδιο του ανθρώπινου πνεύματος κυριαρχούν οι νομικοί και οι άνθρωποι της Εκκλησίας;");

        E2buttonGroup4.add(E2Btn4n1);
        E2Btn4n1.setText("θεολογικό");
        E2Btn4n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Btn4n1ActionPerformed(evt);
            }
        });

        E2buttonGroup4.add(E2Btn4n2);
        E2Btn4n2.setText("μεταφυσικό");
        E2Btn4n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Btn4n2ActionPerformed(evt);
            }
        });

        E2buttonGroup4.add(E2Btn4n3);
        E2Btn4n3.setText("θετικό");
        E2Btn4n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Btn4n3ActionPerformed(evt);
            }
        });

        E2buttonGroup4.add(E2Btn4n4);
        E2Btn4n4.setText("Όλα τα παραπάνω");
        E2Btn4n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Btn4n4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Β) Ερωτήσεις σωστού-λάθους:");

        jLabel7.setText("1) Ο Γάλλος κοινωνιολόγος Κοντ αναγνωρίζεται ως ο “ανάδοχος” της κοινωνιολογίας.");

        E2buttonGroup5.add(E2Sosto1);
        E2Sosto1.setText("Σωστό");
        E2Sosto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Sosto1ActionPerformed(evt);
            }
        });

        E2buttonGroup5.add(E2Lathos1);
        E2Lathos1.setText("Λάθος");
        E2Lathos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Lathos1ActionPerformed(evt);
            }
        });

        jLabel8.setText("2) Στο θεολογικό στάδιο ο άνθρωπος ερμηνεύει τον κόσμο με προσφυγή σε αφηρημένες ιδέες και έννοιες");

        E2buttonGroup6.add(E2Sosto2);
        E2Sosto2.setText("Σωστό");
        E2Sosto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Sosto2ActionPerformed(evt);
            }
        });

        E2buttonGroup6.add(E2Lathos2);
        E2Lathos2.setText("Λάθος");
        E2Lathos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Lathos2ActionPerformed(evt);
            }
        });

        jLabel9.setText("3) Ο Καρλ Μαρξ πίστευε πως οι κοινωνικές επιστήμες θα πρέπει να στοχεύουν στην αλλαγή του κόσμου  και όχι μόνο στη μελέτη του");

        E2buttonGroup7.add(E2Sosto3);
        E2Sosto3.setText("Σωστό");
        E2Sosto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Sosto3ActionPerformed(evt);
            }
        });

        E2buttonGroup7.add(E2Lathos3);
        E2Lathos3.setText("Λάθος");
        E2Lathos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2Lathos3ActionPerformed(evt);
            }
        });

        Submit2Btn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Submit2Btn.setText("Submit");
        Submit2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit2BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(E2Btn4n1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E2Btn4n2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E2Btn4n3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E2Btn4n4))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(E2Btn3n1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E2Btn3n2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E2Btn3n3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E2Btn3n4))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(E2Btn2n1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E2Btn2n2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E2Btn2n3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E2Btn2n4))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(E2Btn1n1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E2Btn1n2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E2Btn1n3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(E2Btn1n4))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(142, 142, 142)
                            .addComponent(E2Sosto1)
                            .addGap(26, 26, 26)
                            .addComponent(E2Lathos1))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addComponent(E2Sosto2)
                            .addGap(26, 26, 26)
                            .addComponent(E2Lathos2))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(E2Sosto3)
                        .addGap(27, 27, 27)
                        .addComponent(E2Lathos3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(Submit2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E2Btn1n1)
                    .addComponent(E2Btn1n2)
                    .addComponent(E2Btn1n3)
                    .addComponent(E2Btn1n4))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E2Btn2n1)
                    .addComponent(E2Btn2n2)
                    .addComponent(E2Btn2n3)
                    .addComponent(E2Btn2n4))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E2Btn3n1)
                    .addComponent(E2Btn3n2)
                    .addComponent(E2Btn3n3)
                    .addComponent(E2Btn3n4))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E2Btn4n1)
                    .addComponent(E2Btn4n2)
                    .addComponent(E2Btn4n3)
                    .addComponent(E2Btn4n4))
                .addGap(29, 29, 29)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E2Sosto1)
                    .addComponent(E2Lathos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E2Sosto2)
                    .addComponent(E2Lathos2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E2Sosto3)
                    .addComponent(E2Lathos3))
                .addGap(34, 34, 34)
                .addComponent(Submit2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit2BtnActionPerformed
        // TODO add your handling code here:
        ExamGui frameT = new ExamGui();
        frameT.setTitle("Διαγώνισμα");
        frameT.setVisible(true);
        frameT.setResizable(true);
        frameT.setLocationRelativeTo(null);
        super.dispose();
        System.out.print("Exam2GUI: " + ans1 + ans2 + ans3 + ans4 + ans5 + ans6 + ans7);
        CreateFile.create();
        WriteToFile.write("Exam2GUI: ");
        WriteToFile.write(ans1 + ans2 + ans3 + ans4 + ans5 + ans6 + ans7);
    }//GEN-LAST:event_Submit2BtnActionPerformed

    private void E2Btn1n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Btn1n1ActionPerformed
        // TODO add your handling code here:
        ans1="true1,";
    }//GEN-LAST:event_E2Btn1n1ActionPerformed

    private void E2Btn1n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Btn1n2ActionPerformed
        // TODO add your handling code here:
        ans1="false1,";
    }//GEN-LAST:event_E2Btn1n2ActionPerformed

    private void E2Btn1n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Btn1n3ActionPerformed
        // TODO add your handling code here:
        ans1="false1,";
    }//GEN-LAST:event_E2Btn1n3ActionPerformed

    private void E2Btn1n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Btn1n4ActionPerformed
        // TODO add your handling code here:
        ans1="false1,";
    }//GEN-LAST:event_E2Btn1n4ActionPerformed

    private void E2Btn2n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Btn2n1ActionPerformed
        // TODO add your handling code here:
        ans2="true2,";
    }//GEN-LAST:event_E2Btn2n1ActionPerformed

    private void E2Btn2n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Btn2n2ActionPerformed
        // TODO add your handling code here:
        ans2="false2,";
    }//GEN-LAST:event_E2Btn2n2ActionPerformed

    private void E2Btn2n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Btn2n3ActionPerformed
        // TODO add your handling code here:
        ans2="false2,";
    }//GEN-LAST:event_E2Btn2n3ActionPerformed

    private void E2Btn2n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Btn2n4ActionPerformed
        // TODO add your handling code here:
        ans2="false2,";
    }//GEN-LAST:event_E2Btn2n4ActionPerformed

    private void E2Btn3n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Btn3n1ActionPerformed
        // TODO add your handling code here:
        ans3="true3,";
    }//GEN-LAST:event_E2Btn3n1ActionPerformed

    private void E2Btn3n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Btn3n2ActionPerformed
        // TODO add your handling code here:
        ans3="false3,";
    }//GEN-LAST:event_E2Btn3n2ActionPerformed

    private void E2Btn3n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Btn3n3ActionPerformed
        // TODO add your handling code here:
        ans3="false3,";
    }//GEN-LAST:event_E2Btn3n3ActionPerformed

    private void E2Btn3n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Btn3n4ActionPerformed
        // TODO add your handling code here:
        ans3="false3,";
    }//GEN-LAST:event_E2Btn3n4ActionPerformed

    private void E2Btn4n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Btn4n1ActionPerformed
        // TODO add your handling code here:
        ans4="false4,";
    }//GEN-LAST:event_E2Btn4n1ActionPerformed

    private void E2Btn4n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Btn4n2ActionPerformed
        // TODO add your handling code here:
        ans4="true4,";
    }//GEN-LAST:event_E2Btn4n2ActionPerformed

    private void E2Btn4n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Btn4n3ActionPerformed
        // TODO add your handling code here:
        ans4="false4,";
    }//GEN-LAST:event_E2Btn4n3ActionPerformed

    private void E2Btn4n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Btn4n4ActionPerformed
        // TODO add your handling code here:
        ans4="false4,";
    }//GEN-LAST:event_E2Btn4n4ActionPerformed

    private void E2Sosto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Sosto1ActionPerformed
        // TODO add your handling code here:
        ans5="true5,";
    }//GEN-LAST:event_E2Sosto1ActionPerformed

    private void E2Lathos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Lathos1ActionPerformed
        // TODO add your handling code here:
        ans5="false5,";
    }//GEN-LAST:event_E2Lathos1ActionPerformed

    private void E2Sosto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Sosto2ActionPerformed
        // TODO add your handling code here:
        ans6="false6,";
    }//GEN-LAST:event_E2Sosto2ActionPerformed

    private void E2Lathos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Lathos2ActionPerformed
        // TODO add your handling code here:
        ans6="true6,";
    }//GEN-LAST:event_E2Lathos2ActionPerformed

    private void E2Sosto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Sosto3ActionPerformed
        // TODO add your handling code here:
        ans7="true7";
    }//GEN-LAST:event_E2Sosto3ActionPerformed

    private void E2Lathos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2Lathos3ActionPerformed
        // TODO add your handling code here:
        ans7="false7";
    }//GEN-LAST:event_E2Lathos3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exam2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exam2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exam2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exam2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exam2GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton E2Btn1n1;
    private javax.swing.JRadioButton E2Btn1n2;
    private javax.swing.JRadioButton E2Btn1n3;
    private javax.swing.JRadioButton E2Btn1n4;
    private javax.swing.JRadioButton E2Btn2n1;
    private javax.swing.JRadioButton E2Btn2n2;
    private javax.swing.JRadioButton E2Btn2n3;
    private javax.swing.JRadioButton E2Btn2n4;
    private javax.swing.JRadioButton E2Btn3n1;
    private javax.swing.JRadioButton E2Btn3n2;
    private javax.swing.JRadioButton E2Btn3n3;
    private javax.swing.JRadioButton E2Btn3n4;
    private javax.swing.JRadioButton E2Btn4n1;
    private javax.swing.JRadioButton E2Btn4n2;
    private javax.swing.JRadioButton E2Btn4n3;
    private javax.swing.JRadioButton E2Btn4n4;
    private javax.swing.JRadioButton E2Lathos1;
    private javax.swing.JRadioButton E2Lathos2;
    private javax.swing.JRadioButton E2Lathos3;
    private javax.swing.JRadioButton E2Sosto1;
    private javax.swing.JRadioButton E2Sosto2;
    private javax.swing.JRadioButton E2Sosto3;
    private javax.swing.ButtonGroup E2buttonGroup1;
    private javax.swing.ButtonGroup E2buttonGroup2;
    private javax.swing.ButtonGroup E2buttonGroup3;
    private javax.swing.ButtonGroup E2buttonGroup4;
    private javax.swing.ButtonGroup E2buttonGroup5;
    private javax.swing.ButtonGroup E2buttonGroup6;
    private javax.swing.ButtonGroup E2buttonGroup7;
    private javax.swing.JButton Submit2Btn;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
