/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testmathisi1;

/**
 *
 * @author babis
 */
public class Exam22GUI extends javax.swing.JFrame {
    String ans1;
    String ans2;
    String ans3;
    String ans4;
    String ans5;
    String ans6;
    String ans7;
    /**
     * Creates new form Exam22GUI
     */
    public Exam22GUI() {
        initComponents();
        ans1="false1,";
        ans2="false2,";
        ans3="false3,";
        ans4="false4,";
        ans5="false5,";
        ans6="false6,";
        ans7="false7";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        E22buttonGroup1 = new javax.swing.ButtonGroup();
        E22buttonGroup2 = new javax.swing.ButtonGroup();
        E22buttonGroup3 = new javax.swing.ButtonGroup();
        E22buttonGroup4 = new javax.swing.ButtonGroup();
        E22buttonGroup5 = new javax.swing.ButtonGroup();
        E22buttonGroup6 = new javax.swing.ButtonGroup();
        E22buttonGroup7 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        E22Btn1n1 = new javax.swing.JRadioButton();
        E22Btn1n2 = new javax.swing.JRadioButton();
        E22Btn1n3 = new javax.swing.JRadioButton();
        E22Btn1n4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        E22Btn2n1 = new javax.swing.JRadioButton();
        E22Btn2n2 = new javax.swing.JRadioButton();
        E22Btn2n3 = new javax.swing.JRadioButton();
        E22Btn2n4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        E22Btn3n1 = new javax.swing.JRadioButton();
        E22Btn3n2 = new javax.swing.JRadioButton();
        E22Btn3n3 = new javax.swing.JRadioButton();
        E22Btn3n4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        E22Btn4n1 = new javax.swing.JRadioButton();
        E22Btn4n2 = new javax.swing.JRadioButton();
        E22Btn4n3 = new javax.swing.JRadioButton();
        E22Btn4n4 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        E22Sosto1 = new javax.swing.JRadioButton();
        E22Lathos1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        E22Sosto2 = new javax.swing.JRadioButton();
        E22Lathos2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        E22Sosto3 = new javax.swing.JRadioButton();
        E22Lathos3 = new javax.swing.JRadioButton();
        Submit22Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Α) Ερωτήσεις πολλαπλής επιλογής:");

        jLabel2.setText("1) Ποιές κοινωνίες στηρίζονταν σε αυτό που ο Ντυρκέμ ονόμασε μηχανική αλληλεγγύη;");

        E22buttonGroup1.add(E22Btn1n1);
        E22Btn1n1.setText("προβιομηχανικές");
        E22Btn1n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Btn1n1ActionPerformed(evt);
            }
        });

        E22buttonGroup1.add(E22Btn1n2);
        E22Btn1n2.setText("μεταβιομηχανικές");
        E22Btn1n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Btn1n2ActionPerformed(evt);
            }
        });

        E22buttonGroup1.add(E22Btn1n3);
        E22Btn1n3.setText("βιομηχανικές");
        E22Btn1n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Btn1n3ActionPerformed(evt);
            }
        });

        E22buttonGroup1.add(E22Btn1n4);
        E22Btn1n4.setText("μη-οργανωμένες");
        E22Btn1n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Btn1n4ActionPerformed(evt);
            }
        });

        jLabel3.setText("2) Που στηρίζονταν οι βιομηχανικές κοινωνίες σύμφωνα με τον Ντυρκέμ; ");

        E22buttonGroup2.add(E22Btn2n1);
        E22Btn2n1.setText("οργανική αλληλεγγύη");
        E22Btn2n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Btn2n1ActionPerformed(evt);
            }
        });

        E22buttonGroup2.add(E22Btn2n2);
        E22Btn2n2.setText("μηχαχνική αλληλεγγύη");
        E22Btn2n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Btn2n2ActionPerformed(evt);
            }
        });

        E22buttonGroup2.add(E22Btn2n3);
        E22Btn2n3.setText("κανένα από τα παραπάνω");
        E22Btn2n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Btn2n3ActionPerformed(evt);
            }
        });

        E22buttonGroup2.add(E22Btn2n4);
        E22Btn2n4.setText("Όλα τα παραπάνω");
        E22Btn2n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Btn2n4ActionPerformed(evt);
            }
        });

        jLabel4.setText("3) Κατά ποιές περιόδους εμφανίζεται η ανομική αυτοκτονία;");

        E22buttonGroup3.add(E22Btn3n1);
        E22Btn3n1.setText("οικονομικής κρίσης");
        E22Btn3n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Btn3n1ActionPerformed(evt);
            }
        });

        E22buttonGroup3.add(E22Btn3n2);
        E22Btn3n2.setText("ευημερίας");
        E22Btn3n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Btn3n2ActionPerformed(evt);
            }
        });

        E22buttonGroup3.add(E22Btn3n3);
        E22Btn3n3.setText("κοινωνικής αποδιοργάνωσης");
        E22Btn3n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Btn3n3ActionPerformed(evt);
            }
        });

        E22buttonGroup3.add(E22Btn3n4);
        E22Btn3n4.setText("Όλα τα παραπάνω");
        E22Btn3n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Btn3n4ActionPerformed(evt);
            }
        });

        jLabel5.setText("4) Τι θέλει να κατανοήσει ο Βέμπερ και κατασκευάζει τους ιδεατούς τύπους ως εργαλεία; ");

        E22buttonGroup4.add(E22Btn4n1);
        E22Btn4n1.setText("κοινωνικές  πράξεις");
        E22Btn4n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Btn4n1ActionPerformed(evt);
            }
        });

        E22buttonGroup4.add(E22Btn4n2);
        E22Btn4n2.setText("κοινωνικά φαινόμενα");
        E22Btn4n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Btn4n2ActionPerformed(evt);
            }
        });

        E22buttonGroup4.add(E22Btn4n3);
        E22Btn4n3.setText("κοινωνικές διαδικασίες");
        E22Btn4n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Btn4n3ActionPerformed(evt);
            }
        });

        E22buttonGroup4.add(E22Btn4n4);
        E22Btn4n4.setText("Όλα τα παραπάνω");
        E22Btn4n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Btn4n4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Β) Ερωτήσεις σωστού-λάθους:");

        jLabel7.setText("1) Η κοινωνική συνοχή των μελών μιας κοινωνίας εκφράζεται ως “κοινωνική αλληλεγγύη” σύμφωνα με  τον Γ. Ντυρκέμ. ");

        E22buttonGroup5.add(E22Sosto1);
        E22Sosto1.setText("Σωστό");
        E22Sosto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Sosto1ActionPerformed(evt);
            }
        });

        E22buttonGroup5.add(E22Lathos1);
        E22Lathos1.setText("Λάθος");
        E22Lathos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Lathos1ActionPerformed(evt);
            }
        });

        jLabel8.setText("2) Σύμφωνα με τον Γ. Ντυρκέμ το σύνολο των αξιών και των κανόνων συγκροτεί τη “συλλογική  συνείδηση”, η οποία δεν καθορίζει τη συμπεριφορά των ανθρώπων.");

        E22buttonGroup6.add(E22Sosto2);
        E22Sosto2.setText("Σωστό");
        E22Sosto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Sosto2ActionPerformed(evt);
            }
        });

        E22buttonGroup6.add(E22Lathos2);
        E22Lathos2.setText("Λάθος");
        E22Lathos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Lathos2ActionPerformed(evt);
            }
        });

        jLabel9.setText("3) Η οργανική αλληλεγγύη δεν βασίζεται στον υχηλό καταμερισμό εργασίας ανάμεσα σε εξειδικευμένους  ρόλους.");

        E22buttonGroup7.add(E22Sosto3);
        E22Sosto3.setText("Σωστό");
        E22Sosto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Sosto3ActionPerformed(evt);
            }
        });

        E22buttonGroup7.add(E22Lathos3);
        E22Lathos3.setText("Λαθός");
        E22Lathos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E22Lathos3ActionPerformed(evt);
            }
        });

        Submit22Btn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Submit22Btn.setText("Submit");
        Submit22Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit22BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(E22Btn1n1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(E22Btn1n2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(E22Btn1n3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(E22Btn1n4))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(E22Btn2n1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(E22Btn2n2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(E22Btn2n3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(E22Btn2n4))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(E22Btn3n1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E22Btn3n2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E22Btn3n3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E22Btn3n4)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(E22Btn4n1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E22Btn4n2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E22Btn4n3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E22Btn4n4)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(E22Sosto1)
                        .addGap(18, 18, 18)
                        .addComponent(E22Lathos1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(E22Sosto2)
                        .addGap(18, 18, 18)
                        .addComponent(E22Lathos2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(E22Sosto3)
                        .addGap(18, 18, 18)
                        .addComponent(E22Lathos3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(Submit22Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E22Btn1n1)
                    .addComponent(E22Btn1n2)
                    .addComponent(E22Btn1n3)
                    .addComponent(E22Btn1n4))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E22Btn2n1)
                    .addComponent(E22Btn2n2)
                    .addComponent(E22Btn2n3)
                    .addComponent(E22Btn2n4))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E22Btn3n1)
                    .addComponent(E22Btn3n2)
                    .addComponent(E22Btn3n3)
                    .addComponent(E22Btn3n4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E22Btn4n1)
                    .addComponent(E22Btn4n2)
                    .addComponent(E22Btn4n3)
                    .addComponent(E22Btn4n4))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E22Sosto1)
                    .addComponent(E22Lathos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E22Sosto2)
                    .addComponent(E22Lathos2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E22Sosto3)
                    .addComponent(E22Lathos3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(Submit22Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit22BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit22BtnActionPerformed
       
        ExamGui frameT = new ExamGui();
        frameT.setTitle("Διαγώνισμα");
        frameT.setVisible(true);
        frameT.setResizable(true);
        frameT.setLocationRelativeTo(null);
        super.dispose();
        System.out.print("Exam22GUI: " + ans1 + ans2 + ans3 + ans4 + ans5 + ans6 + ans7);
        CreateFile.create();
        WriteToFile.write("Exam22GUI: ");
        WriteToFile.write(ans1 + ans2 + ans3 + ans4 + ans5 + ans6 + ans7);
    }//GEN-LAST:event_Submit22BtnActionPerformed

    private void E22Btn1n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Btn1n1ActionPerformed
        // TODO add your handling code here:
        ans1="true1,";
    }//GEN-LAST:event_E22Btn1n1ActionPerformed

    private void E22Btn1n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Btn1n2ActionPerformed
        // TODO add your handling code here:
        ans1="false1,";
    }//GEN-LAST:event_E22Btn1n2ActionPerformed

    private void E22Btn1n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Btn1n3ActionPerformed
        // TODO add your handling code here:
        ans1="false1,";
    }//GEN-LAST:event_E22Btn1n3ActionPerformed

    private void E22Btn1n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Btn1n4ActionPerformed
        // TODO add your handling code here:
        ans1="false1,";
    }//GEN-LAST:event_E22Btn1n4ActionPerformed

    private void E22Btn2n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Btn2n1ActionPerformed
        // TODO add your handling code here:
        ans2="true2,";
    }//GEN-LAST:event_E22Btn2n1ActionPerformed

    private void E22Btn2n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Btn2n2ActionPerformed
        // TODO add your handling code here:
        ans2="false2,";
    }//GEN-LAST:event_E22Btn2n2ActionPerformed

    private void E22Btn2n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Btn2n3ActionPerformed
        // TODO add your handling code here:
        ans2="false2,";
    }//GEN-LAST:event_E22Btn2n3ActionPerformed

    private void E22Btn3n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Btn3n1ActionPerformed
        // TODO add your handling code here:
        ans3="false3,";
    }//GEN-LAST:event_E22Btn3n1ActionPerformed

    private void E22Btn3n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Btn3n2ActionPerformed
        // TODO add your handling code here:
        ans3="false3,";
    }//GEN-LAST:event_E22Btn3n2ActionPerformed

    private void E22Btn3n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Btn3n3ActionPerformed
        // TODO add your handling code here:
        ans3="true3,";
    }//GEN-LAST:event_E22Btn3n3ActionPerformed

    private void E22Btn3n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Btn3n4ActionPerformed
        // TODO add your handling code here:
        ans3="false3,";
    }//GEN-LAST:event_E22Btn3n4ActionPerformed

    private void E22Btn4n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Btn4n1ActionPerformed
        // TODO add your handling code here:
        ans3="false4,";
    }//GEN-LAST:event_E22Btn4n1ActionPerformed

    private void E22Btn4n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Btn4n2ActionPerformed
        // TODO add your handling code here:
        ans4="false4,";
    }//GEN-LAST:event_E22Btn4n2ActionPerformed

    private void E22Btn4n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Btn4n3ActionPerformed
        // TODO add your handling code here:
        ans4="false4,";
    }//GEN-LAST:event_E22Btn4n3ActionPerformed

    private void E22Btn4n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Btn4n4ActionPerformed
        // TODO add your handling code here:
        ans4="false4,";
    }//GEN-LAST:event_E22Btn4n4ActionPerformed

    private void E22Sosto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Sosto1ActionPerformed
        // TODO add your handling code here:
        ans5="true5,";
    }//GEN-LAST:event_E22Sosto1ActionPerformed

    private void E22Lathos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Lathos1ActionPerformed
        // TODO add your handling code here:
        ans5="falsee5,";
    }//GEN-LAST:event_E22Lathos1ActionPerformed

    private void E22Sosto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Sosto2ActionPerformed
        // TODO add your handling code here:
        ans6="false6,";
    }//GEN-LAST:event_E22Sosto2ActionPerformed

    private void E22Lathos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Lathos2ActionPerformed
        // TODO add your handling code here:
        ans6="true6,";
    }//GEN-LAST:event_E22Lathos2ActionPerformed

    private void E22Sosto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Sosto3ActionPerformed
        // TODO add your handling code here:
        ans7="false7";
    }//GEN-LAST:event_E22Sosto3ActionPerformed

    private void E22Lathos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Lathos3ActionPerformed
        // TODO add your handling code here:
        ans7="true7";
    }//GEN-LAST:event_E22Lathos3ActionPerformed

    private void E22Btn2n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E22Btn2n4ActionPerformed
        // TODO add your handling code here:
        ans2="true2,";
    }//GEN-LAST:event_E22Btn2n4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exam22GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exam22GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exam22GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exam22GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exam22GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton E22Btn1n1;
    private javax.swing.JRadioButton E22Btn1n2;
    private javax.swing.JRadioButton E22Btn1n3;
    private javax.swing.JRadioButton E22Btn1n4;
    private javax.swing.JRadioButton E22Btn2n1;
    private javax.swing.JRadioButton E22Btn2n2;
    private javax.swing.JRadioButton E22Btn2n3;
    private javax.swing.JRadioButton E22Btn2n4;
    private javax.swing.JRadioButton E22Btn3n1;
    private javax.swing.JRadioButton E22Btn3n2;
    private javax.swing.JRadioButton E22Btn3n3;
    private javax.swing.JRadioButton E22Btn3n4;
    private javax.swing.JRadioButton E22Btn4n1;
    private javax.swing.JRadioButton E22Btn4n2;
    private javax.swing.JRadioButton E22Btn4n3;
    private javax.swing.JRadioButton E22Btn4n4;
    private javax.swing.JRadioButton E22Lathos1;
    private javax.swing.JRadioButton E22Lathos2;
    private javax.swing.JRadioButton E22Lathos3;
    private javax.swing.JRadioButton E22Sosto1;
    private javax.swing.JRadioButton E22Sosto2;
    private javax.swing.JRadioButton E22Sosto3;
    private javax.swing.ButtonGroup E22buttonGroup1;
    private javax.swing.ButtonGroup E22buttonGroup2;
    private javax.swing.ButtonGroup E22buttonGroup3;
    private javax.swing.ButtonGroup E22buttonGroup4;
    private javax.swing.ButtonGroup E22buttonGroup5;
    private javax.swing.ButtonGroup E22buttonGroup6;
    private javax.swing.ButtonGroup E22buttonGroup7;
    private javax.swing.JButton Submit22Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
